/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FundingFactory {
  export type FundingDetailsStruct = {
    contractAddress: AddressLike;
    purpose: string;
  };

  export type FundingDetailsStructOutput = [
    contractAddress: string,
    purpose: string
  ] & { contractAddress: string; purpose: string };
}

export interface FundingFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createCrowdFundingContract"
      | "deployedContracts"
      | "fundingFee"
      | "getUserdeployedContracts"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NewCrowdFundingCreated" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createCrowdFundingContract",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedContracts",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserdeployedContracts",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createCrowdFundingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundingFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserdeployedContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace NewCrowdFundingCreatedEvent {
  export type InputTuple = [
    owner: AddressLike,
    amount: BigNumberish,
    cloneAddress: AddressLike,
    fundingCID: string
  ];
  export type OutputTuple = [
    owner: string,
    amount: bigint,
    cloneAddress: string,
    fundingCID: string
  ];
  export interface OutputObject {
    owner: string;
    amount: bigint;
    cloneAddress: string;
    fundingCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FundingFactory extends BaseContract {
  connect(runner?: ContractRunner | null): FundingFactory;
  waitForDeployment(): Promise<this>;

  interface: FundingFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createCrowdFundingContract: TypedContractMethod<
    [
      _fundingCId: string,
      _purpose: string,
      _amount: BigNumberish,
      _duration: BigNumberish
    ],
    [void],
    "payable"
  >;

  deployedContracts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [[string, string] & { contractAddress: string; purpose: string }],
    "view"
  >;

  fundingFee: TypedContractMethod<[], [bigint], "view">;

  getUserdeployedContracts: TypedContractMethod<
    [],
    [FundingFactory.FundingDetailsStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createCrowdFundingContract"
  ): TypedContractMethod<
    [
      _fundingCId: string,
      _purpose: string,
      _amount: BigNumberish,
      _duration: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deployedContracts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [[string, string] & { contractAddress: string; purpose: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserdeployedContracts"
  ): TypedContractMethod<
    [],
    [FundingFactory.FundingDetailsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "NewCrowdFundingCreated"
  ): TypedContractEvent<
    NewCrowdFundingCreatedEvent.InputTuple,
    NewCrowdFundingCreatedEvent.OutputTuple,
    NewCrowdFundingCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "NewCrowdFundingCreated(address,uint256,address,string)": TypedContractEvent<
      NewCrowdFundingCreatedEvent.InputTuple,
      NewCrowdFundingCreatedEvent.OutputTuple,
      NewCrowdFundingCreatedEvent.OutputObject
    >;
    NewCrowdFundingCreated: TypedContractEvent<
      NewCrowdFundingCreatedEvent.InputTuple,
      NewCrowdFundingCreatedEvent.OutputTuple,
      NewCrowdFundingCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
